volumes:
  postgres_data:
    driver: local

services:
  postgres-container:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5444:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
  traefik:
    image: traefik:2.9
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      #- "--entrypoints.websecure.address=:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - ${HTTP_PORT:-80}:80
      #- ${HTTPS_PORT:-443}:443
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres-container
      DB_SCHEMA: public
    env_file:
      - .env
        # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
        #JDBC_PARAMS: "ssl=true"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak.rule=Host(`localhost`)"
      - "traefik.http.routers.keycloak.entrypoints=web"
    ports:
      - 8080:8080
    depends_on:
      - postgres-container
    command:
      [
        "start-dev",
        "--debug",
        "--features=client-policies",
        "--db",
        "postgres",
        "--db-url",
        "jdbc:postgresql://postgres-container/${POSTGRES_DB}",
        "--db-username",
        "${POSTGRES_USER}",
        "--db-password",
        "${POSTGRES_PASSWORD}",
      ]
    volumes:
      - ./keycloak-restrict-client-auth.jar:/opt/keycloak/providers/keycloak-restrict-client-auth.jar
      - ./keycloak-restrict-client-auth-20.0.1/src/test/resources/:/tmp/import
